//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SN_Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.cloud_srv_Recby = new HashSet<cloud_srv>();
            this.d_msg_Recby = new HashSet<d_msg>();
            this.dealer_Recby = new HashSet<dealer>();
            this.event_calendar_Recby = new HashSet<event_calendar>();
            this.event_calendar_Users_id = new HashSet<event_calendar>();
            this.istab_Recby = new HashSet<istab>();
            this.ma_Recby = new HashSet<ma>();
            this.note_calendar_Recby = new HashSet<note_calendar>();
            this.problem_Recby = new HashSet<problem>();
            this.serial_Recby = new HashSet<serial>();
            this.serial_password_Recby = new HashSet<serial_password>();
            this.spy_log_Users_id = new HashSet<spy_log>();
            this.training_calendar_Recby = new HashSet<training_calendar>();
            this.training_calendar_Users_id = new HashSet<training_calendar>();
            this.websession_Users_id = new HashSet<websession>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int level { get; set; }
        public string usergroup { get; set; }
        public string status { get; set; }
        public string allowed_web_login { get; set; }
        public string training_expert { get; set; }
        public int max_absent { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<System.DateTime> last_use { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cloud_srv> cloud_srv_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<d_msg> d_msg_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealer> dealer_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_calendar> event_calendar_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_calendar> event_calendar_Users_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<istab> istab_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma> ma_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<note_calendar> note_calendar_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<problem> problem_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serial> serial_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serial_password> serial_password_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spy_log> spy_log_Users_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_calendar> training_calendar_Recby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<training_calendar> training_calendar_Users_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<websession> websession_Users_id { get; set; }
    }
}
